# .github/workflows/build-pages.yml
name: build-and-publish
on:
  push:
    branches: [ main ]
permissions:
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: System deps
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg libcairo2 libpango-1.0-0 pkg-config \
            texlive-latex-base texlive-latex-recommended texlive-latex-extra \
            texlive-fonts-extra texlive-science dvipng

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv + deps
        run: |
          python -m pip install -U pip uv
          uv venv .venv
          source .venv/bin/activate
          uv pip install "manim-slides[manim]" PySide6 pandas

      - name: Build slides + HTML
        run: |
          chmod +x scripts/build_slides.sh
          source .venv/bin/activate
          ./scripts/build_slides.sh all --scenes-file scenes.list --site site --pythonpath .

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
