name: build-and-publish
on:
  push:
    branches: [ master ]
permissions:
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: System deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential pkg-config \
            libcairo2-dev libpango1.0-dev libglib2.0-dev libharfbuzz-dev \
            libfreetype6-dev libfontconfig1-dev libfribidi-dev \
            ffmpeg \
            texlive-xetex latexmk \
            texlive-latex-base texlive-latex-recommended texlive-latex-extra \
            texlive-fonts-extra texlive-science dvipng \
            fonts-noto

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv + deps
        run: |
          python -m pip install -U pip uv
          uv venv .venv
          source .venv/bin/activate
          uv pip install "manim-slides[manim]" PySide6 pandas

      - name: Build slides + HTML
        run: |
          source .venv/bin/activate
          ./scripts/build_slides.sh all --scenes-file scenes.list --site site --pythonpath .

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site   # contains index.html (+ assets if not --one-file)

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
